version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-groupsapp}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - JWT_SECRET=${JWT_SECRET:-tu_secreto_jwt}
      - DB_NAME=${DB_NAME:-groupsapp}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_HOST=db
    depends_on:
      - db

volumes:
  postgres_data: